"""
PDF report generator for the Skin Disease Detection System.
Uses FPDF2 to create downloadable diagnostic reports.
"""

import io
from datetime import datetime
from typing import Any, Optional

from fpdf import FPDF

from utils.logger import get_logger

logger = get_logger(__name__)


class ReportPDF(FPDF):
    """Custom PDF class with header and footer for medical reports."""

    def header(self) -> None:
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(41, 128, 185)
        self.cell(0, 10, "AI Skin Disease Detection Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(41, 128, 185)
        self.line(10, 22, 200, 22)
        self.ln(8)

    def footer(self) -> None:
        self.set_y(-30)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.multi_cell(
            0,
            4,
            "DISCLAIMER: This report is generated by an AI system for educational purposes only. "
            "It does not constitute medical advice and should not replace consultation with a "
            "qualified dermatologist. Always seek professional medical guidance for skin concerns.",
            align="C",
        )
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="C")


def _sanitize(text: str) -> str:
    """Strip characters unsupported by Helvetica (latin-1 only)."""
    return text.encode("latin-1", errors="replace").decode("latin-1")


def _add_section(pdf: ReportPDF, title: str, content: str) -> None:
    """Add a titled section to the PDF."""
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(44, 62, 80)
    pdf.cell(0, 8, _sanitize(title), new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(189, 195, 199)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(52, 73, 94)
    pdf.multi_cell(0, 5, _sanitize(content))
    pdf.ln(4)


def generate_pdf_report(
    prediction: dict[str, Any],
    risk_result: dict[str, Any],
    patient_info: dict[str, Any],
    llm_analysis: Optional[str] = None,
) -> bytes:
    """
    Generate a PDF diagnostic report.

    Args:
        prediction: Dict with keys: label, confidence, cancer_probability, warnings.
        risk_result: Dict with keys: risk_level, reasoning.
        patient_info: Dict with patient metadata (age, gender, etc.).
        llm_analysis: Optional LLM-generated analysis text.

    Returns:
        PDF file content as bytes.
    """
    try:
        pdf = ReportPDF()
        pdf.alias_nb_pages()
        pdf.add_page()

        # Report metadata
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(0, 5, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        # Prediction section
        confidence = prediction.get("confidence", 0)
        cancer_prob = prediction.get("cancer_probability", 0)
        pred_text = (
            f"Predicted Condition: {prediction.get('label', 'Unknown')}\n"
            f"Model Confidence: {confidence:.1%}\n"
            f"Cancer Probability: {cancer_prob:.1%}\n"
        )
        warnings = prediction.get("warnings", [])
        if warnings:
            pred_text += "\nWarnings:\n" + "\n".join(f"  - {w}" for w in warnings)

        _add_section(pdf, "AI Prediction", pred_text)

        # Risk assessment section
        risk_text = (
            f"Risk Level: {risk_result.get('risk_level', 'Unknown')}\n\n"
            f"Reasoning:\n{risk_result.get('reasoning', 'N/A')}"
        )
        _add_section(pdf, "Risk Assessment", risk_text)

        # Patient information section
        patient_lines = []
        field_labels = {
            "age": "Age",
            "gender": "Gender",
            "duration": "Lesion Duration",
            "itching": "Itching",
            "bleeding": "Bleeding",
            "size_change": "Change in Size",
            "family_history": "Family History of Skin Cancer",
            "pain_level": "Pain Level",
        }
        for key, label in field_labels.items():
            val = patient_info.get(key, "N/A")
            patient_lines.append(f"{label}: {val}")
        _add_section(pdf, "Patient Information", "\n".join(patient_lines))

        # LLM analysis section
        if llm_analysis:
            _add_section(pdf, "AI Analysis & Recommendations", llm_analysis)

        # Output
        pdf_bytes = pdf.output()
        if isinstance(pdf_bytes, str):
            pdf_bytes = pdf_bytes.encode("latin-1")

        logger.info("PDF report generated successfully")
        return bytes(pdf_bytes)

    except Exception as e:
        logger.error(f"Failed to generate PDF report: {e}")
        raise
