"""
Vision-enhanced LLM analysis for skin disease predictions.

Uses a 3-step pipeline:
  1. Open-ended vision diagnosis (LLaMA 4 Scout sees the actual image)
  2. Internet search (Tavily searches for the identified condition)
  3. Combined analysis (LLM synthesizes classifier + vision + search + patient data)

This handles rare conditions that the classifier's fixed label set cannot predict.
"""

import base64
import io
import json
import re
from typing import Any, Optional

from PIL import Image
from langchain_core.messages import HumanMessage, SystemMessage

from utils.config import Config
from utils.logger import get_logger

logger = get_logger(__name__)

VISION_MODEL = "meta-llama/llama-4-scout-17b-16e-instruct"

# ── Prompts ────────────────────────────────────────────────────────

VISION_DIAGNOSIS_PROMPT = """You are an expert dermatologist analyzing a clinical skin image.

Examine this image carefully. Do NOT limit yourself to common conditions.
Consider rare and uncommon conditions too, such as:
- Epidermodysplasia verruciformis
- Cutaneous horns
- Porokeratosis
- Mycosis fungoides
- Kaposi sarcoma
- Harlequin ichthyosis
- etc.

Respond with ONLY valid JSON (no markdown fences):
{
  "diagnosis": "most likely condition name",
  "confidence": "high/medium/low",
  "differential_diagnoses": ["alternative 1", "alternative 2"],
  "visual_description": "describe what you see in detail",
  "reasoning": "explain why you think this is the diagnosis",
  "is_rare": true/false,
  "severity": "mild/moderate/severe/critical",
  "search_query": "best search query for this condition"
}
"""

ANALYSIS_SYSTEM_PROMPT = """You are an expert AI dermatology assistant providing comprehensive analysis.

You receive data from MULTIPLE sources:
1. An AI classifier with fixed labels (may be wrong for rare conditions)
2. A vision AI that independently examined the image (can identify rare conditions)
3. Internet search results about the identified condition
4. A curated medical knowledge base
5. Patient-reported symptoms and history

YOUR JOB:
- COMPARE the classifier output with the vision model's independent diagnosis
- If they DISAGREE, explain why and weigh which is more likely correct
- If the vision model identifies a RARE condition, prioritize that over the classifier
- Include information from internet search results when available
- Always provide actionable medical guidance

CRITICAL SAFETY RULES:
1. NEVER claim a definitive diagnosis. Use "suggests", "may indicate", "consistent with".
2. ALWAYS recommend consulting a qualified dermatologist.
3. If cancer probability or severity is high, URGENTLY recommend professional consultation.
4. For rare conditions, emphasize the importance of specialist evaluation.

YOUR ANALYSIS MUST INCLUDE:
1. **Vision AI Assessment**: What the AI sees in the image (independent of the classifier)
2. **Classifier vs Vision Comparison**: Do they agree? If not, which is more reliable?
3. **Condition Overview**: Explain the most likely condition in simple terms
4. **Risk Assessment**: Interpret severity and urgency
5. **Key Observations**: Concerning symptoms from patient data
6. **Internet Research**: Relevant findings from web search (if available)
7. **Recommended Actions**: Clear next steps (always include "consult a dermatologist")

FORMAT: Use clear markdown with headers and bullet points.

ALWAYS end with:
"Disclaimer: This analysis is generated by an AI system for educational purposes only. It does not constitute medical advice, diagnosis, or treatment recommendation. Always consult a qualified dermatologist or healthcare provider for any skin concerns."
"""


def _get_groq_client(config: Config):
    """Get a Groq client instance."""
    if not config.has_groq:
        raise ValueError("Groq API key is required. Set GROQ_API_KEY in .env")
    from groq import Groq
    return Groq(api_key=config.groq_api_key)


def _get_llm(config: Config):
    """Initialize the LangChain LLM for text analysis."""
    if config.has_groq:
        try:
            from langchain_groq import ChatGroq
            llm = ChatGroq(
                model=config.llm_model,
                temperature=config.llm_temperature,
                api_key=config.groq_api_key,
                max_tokens=2048,
            )
            logger.info(f"Using Groq LLM: {config.llm_model}")
            return llm
        except Exception as e:
            logger.warning(f"Failed to initialize Groq LLM: {e}")

    raise ValueError("No LLM API key available. Please provide a Groq API key.")


def _image_to_base64(image: Image.Image, max_size: int = 512) -> str:
    """Convert PIL Image to base64 JPEG, resized for API efficiency."""
    img = image.copy()
    img.thumbnail((max_size, max_size), Image.Resampling.LANCZOS)
    buf = io.BytesIO()
    img.save(buf, format="JPEG", quality=85)
    return base64.b64encode(buf.getvalue()).decode("utf-8")


# ── Step 1: Vision Diagnosis ──────────────────────────────────────

def _vision_diagnosis(config: Config, image: Image.Image) -> dict[str, Any]:
    """
    Send the image to the vision model for an open-ended diagnosis.
    Not limited to fixed labels — can identify rare conditions.
    """
    try:
        client = _get_groq_client(config)
        img_b64 = _image_to_base64(image)

        logger.info("Step 1: Getting independent vision diagnosis...")

        response = client.chat.completions.create(
            model=VISION_MODEL,
            messages=[{
                "role": "user",
                "content": [
                    {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}},
                    {"type": "text", "text": VISION_DIAGNOSIS_PROMPT},
                ],
            }],
            temperature=0.1,
            max_tokens=600,
        )

        raw = response.choices[0].message.content.strip()
        raw = re.sub(r'^```(?:json)?\s*', '', raw)
        raw = re.sub(r'\s*```$', '', raw)

        result = json.loads(raw)
        logger.info(f"Vision diagnosis: {result.get('diagnosis', 'unknown')}")
        return result

    except json.JSONDecodeError:
        logger.warning("Could not parse vision diagnosis JSON, using raw text")
        return {
            "diagnosis": "unknown",
            "visual_description": raw if 'raw' in dir() else "Analysis unavailable",
            "confidence": "low",
            "differential_diagnoses": [],
            "is_rare": False,
            "severity": "unknown",
            "search_query": "skin lesion diagnosis",
        }
    except Exception as e:
        logger.error(f"Vision diagnosis failed: {e}")
        return {
            "diagnosis": "unavailable",
            "visual_description": f"Vision analysis failed: {str(e)}",
            "confidence": "none",
            "differential_diagnoses": [],
            "is_rare": False,
            "severity": "unknown",
            "search_query": "skin lesion",
        }


# ── Step 2: Internet Search ──────────────────────────────────────

def _search_condition(config: Config, vision_result: dict) -> str:
    """
    Search Tavily for information about the vision model's diagnosis.
    """
    if not config.has_tavily:
        logger.warning("Tavily API key not set — skipping internet search")
        return ""

    diagnosis = vision_result.get("diagnosis", "")
    search_query = vision_result.get("search_query", diagnosis)
    if not search_query or search_query == "unknown":
        return ""

    try:
        from tavily import TavilyClient

        client = TavilyClient(api_key=config.tavily_api_key)
        logger.info(f"Step 2: Searching internet for: {search_query}")

        response = client.search(
            query=f"{search_query} dermatology skin condition symptoms treatment",
            search_depth="basic",
            max_results=3,
            include_answer=True,
        )

        results = []
        if response.get("answer"):
            results.append(f"**Summary:** {response['answer']}")

        for item in response.get("results", [])[:3]:
            title = item.get("title", "")
            content = item.get("content", "")[:400]
            url = item.get("url", "")
            results.append(f"**{title}**\n{content}\nSource: {url}")

        search_text = "\n\n---\n\n".join(results)
        logger.info(f"Internet search returned {len(results)} results")
        return search_text

    except Exception as e:
        logger.error(f"Internet search failed: {e}")
        return f"Internet search failed: {str(e)}"


# ── Step 3: Medical Knowledge Lookup ──────────────────────────────

def _fetch_medical_context(condition: str) -> str:
    """Keyword-based lookup from curated medical knowledge corpus."""
    try:
        from rag.medical_knowledge import get_medical_documents

        docs = get_medical_documents()
        condition_lower = condition.lower()

        matched = []
        for doc in docs:
            topic = doc["metadata"].get("topic", "").lower()
            content = doc["content"].lower()
            if condition_lower in topic or topic in condition_lower or condition_lower in content:
                source = doc["metadata"].get("source", "Unknown")
                topic_name = doc["metadata"].get("topic", "Unknown")
                matched.append(f"[{source}] {topic_name}\n{doc['content']}")

        # Always include prevention/guidance
        for doc in docs:
            topic = doc["metadata"].get("topic", "").lower()
            if topic in ("skin cancer prevention", "when to see a doctor"):
                source = doc["metadata"].get("source", "Unknown")
                topic_name = doc["metadata"].get("topic", "Unknown")
                entry = f"[{source}] {topic_name}\n{doc['content']}"
                if entry not in matched:
                    matched.append(entry)

        return "\n\n---\n\n".join(matched[:4]) if matched else ""

    except Exception as e:
        logger.warning(f"Medical knowledge lookup failed: {e}")
        return ""


# ── Main Analysis Function ────────────────────────────────────────

def analyze_prediction(
    config: Config,
    prediction: dict[str, Any],
    risk_result: dict[str, Any],
    patient_info: dict[str, Any],
    image: Optional[Image.Image] = None,
) -> str:
    """
    Run the full 3-step vision-enhanced analysis pipeline.

    Steps:
      1. Open-ended vision diagnosis (if image provided)
      2. Internet search for the identified condition
      3. Combined LLM analysis with all data sources
    """
    try:
        # Step 1: Vision diagnosis
        vision_result = {}
        if image is not None:
            vision_result = _vision_diagnosis(config, image)

        # Step 2: Internet search based on vision diagnosis
        search_results = ""
        if vision_result.get("diagnosis") and vision_result["diagnosis"] not in ("unknown", "unavailable"):
            search_results = _search_condition(config, vision_result)

        # Step 3: Medical knowledge lookup
        # Look up both the classifier's prediction AND the vision model's diagnosis
        classifier_condition = prediction.get("label", "unknown")
        vision_condition = vision_result.get("diagnosis", "")
        medical_context = _fetch_medical_context(classifier_condition)
        if vision_condition and vision_condition.lower() != classifier_condition.lower():
            extra_context = _fetch_medical_context(vision_condition)
            if extra_context:
                medical_context += "\n\n---\n\n" + extra_context

        # Step 4: Combined analysis
        llm = _get_llm(config)
        prompt = _build_combined_prompt(
            prediction, risk_result, patient_info,
            vision_result, search_results, medical_context,
        )

        logger.info("Step 3: Running combined analysis LLM...")

        response = llm.invoke([
            SystemMessage(content=ANALYSIS_SYSTEM_PROMPT),
            HumanMessage(content=prompt),
        ])

        result = response.content if hasattr(response, "content") else str(response)
        logger.info("Combined analysis complete")
        return result

    except ValueError as e:
        return str(e)
    except Exception as e:
        logger.error(f"Analysis failed: {e}")
        return (
            f"AI analysis could not be completed: {str(e)}\n\n"
            "Please ensure your API keys are valid and try again.\n\n"
            "Disclaimer: This system is for educational purposes only. "
            "Always consult a qualified dermatologist for skin concerns."
        )


def chat_followup(config: Config, question: str, context: str) -> str:
    """Handle a follow-up chat question about a previous analysis."""
    try:
        llm = _get_llm(config)
        prompt = (
            f"The user previously received this skin disease analysis:\n\n"
            f"---\n{context}\n---\n\n"
            f"The user now asks: {question}\n\n"
            f"Provide a helpful, medically-safe response. Always include the disclaimer."
        )
        response = llm.invoke([
            SystemMessage(content=ANALYSIS_SYSTEM_PROMPT),
            HumanMessage(content=prompt),
        ])
        return response.content if hasattr(response, "content") else str(response)
    except Exception as e:
        logger.error(f"Follow-up chat failed: {e}")
        return f"Could not process your question: {str(e)}"


# ── Prompt Builder ────────────────────────────────────────────────

def _build_combined_prompt(
    prediction: dict[str, Any],
    risk_result: dict[str, Any],
    patient_info: dict[str, Any],
    vision_result: dict[str, Any],
    search_results: str,
    medical_context: str,
) -> str:
    """Build the comprehensive prompt that combines all data sources."""

    # Classifier predictions
    warnings_text = ""
    warnings = prediction.get("warnings", [])
    if warnings:
        warnings_text = "\n**WARNINGS:**\n" + "\n".join(f"- {w}" for w in warnings)

    all_preds = prediction.get("all_predictions", [])
    all_preds_text = "\n".join(
        f"  - {p['label']}: {p['score']:.1%}" for p in all_preds[:5]
    ) if all_preds else "N/A"

    components = risk_result.get("components", {})
    components_text = "\n".join(
        f"  - {k.replace('_', ' ').title()}: {v}" for k, v in components.items()
    )

    # Vision diagnosis section
    vision_section = ""
    if vision_result:
        diff_diag = vision_result.get("differential_diagnoses", [])
        diff_text = ", ".join(diff_diag) if diff_diag else "None"
        vision_section = f"""
## Vision AI Independent Diagnosis
The vision AI examined the actual image independently (not limited to fixed labels):
- **Diagnosis:** {vision_result.get('diagnosis', 'N/A')}
- **Confidence:** {vision_result.get('confidence', 'N/A')}
- **Severity:** {vision_result.get('severity', 'N/A')}
- **Is Rare Condition:** {vision_result.get('is_rare', False)}
- **Visual Description:** {vision_result.get('visual_description', 'N/A')}
- **Reasoning:** {vision_result.get('reasoning', 'N/A')}
- **Differential Diagnoses:** {diff_text}
"""

    # Internet search section
    search_section = ""
    if search_results:
        search_section = f"""
## Internet Research Results
The following was found by searching the internet for the vision AI's diagnosis:

{search_results}
"""

    # Medical knowledge section
    knowledge_section = ""
    if medical_context:
        knowledge_section = f"""
## Curated Medical Knowledge Base
From trusted sources (WHO, NIH, Mayo Clinic):

{medical_context}
"""

    return f"""Analyze the following skin condition using ALL available data sources.

## AI Classifier Prediction (fixed label set — may be wrong for rare conditions)
- **Predicted Condition:** {prediction.get('label', 'Unknown')}
- **Model Confidence:** {prediction.get('confidence', 0):.1%}
- **Cancer Probability:** {prediction.get('cancer_probability', 0):.1%}
- **Is Cancerous Type:** {prediction.get('is_cancerous', False)}
{warnings_text}

### All Classifier Predictions:
{all_preds_text}
{vision_section}
## Risk Assessment
- **Risk Level:** {risk_result.get('risk_level', 'Unknown')}
- **Risk Score:** {risk_result.get('risk_score', 0):.3f}/1.000
- **Components:**
{components_text}

### Reasoning:
{risk_result.get('reasoning', 'N/A')}

## Patient Information
- **Age:** {patient_info.get('age', 'N/A')}
- **Gender:** {patient_info.get('gender', 'N/A')}
- **Lesion Duration:** {patient_info.get('duration', 'N/A')}
- **Itching:** {'Yes' if patient_info.get('itching') else 'No'}
- **Bleeding:** {'Yes' if patient_info.get('bleeding') else 'No'}
- **Change in Size:** {'Yes' if patient_info.get('size_change') else 'No'}
- **Family History:** {'Yes' if patient_info.get('family_history') else 'No'}
- **Pain Level:** {patient_info.get('pain_level', 'N/A')}/10
{search_section}
{knowledge_section}
IMPORTANT: If the classifier and vision AI disagree, carefully explain BOTH perspectives and indicate which is more likely correct based on the visual evidence and search results. For rare conditions, the vision AI's assessment takes priority over the fixed-label classifier.

Provide a comprehensive analysis covering all sections described in your instructions.
"""
